version: '3.4'

services:
  fastapi:
    build: .
    container_name: letoctf_fastapi
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: letoctf_postgres
    environment:
      POSTGRES_DB: "hackathon"
      POSTGRES_USER: "secretuser"
      POSTGRES_PASSWORD: "secretpassword"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U secretuser -d secretpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
    external:
      name: traefik_network
