version: '3.4'

services:
  fastapi:
    build: .
    container_name: letoctf_fastapi
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letoctf_fastapi.rule=Host(`gachi.abakumov.life`)"
      - "traefik.http.routers.letoctf_fastapi.entrypoints=websecure"
      - "traefik.http.routers.letoctf_fastapi.tls=true"
      - "traefik.http.routers.letoctf_fastapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.letoctf_fastapi.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_network"

  postgres:
    image: postgres
    container_name: letoctf_postgres
    environment:
      POSTGRES_DB: "hackathon"
      POSTGRES_USER: "secretuser"
      POSTGRES_PASSWORD: "secretpassword"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U secretuser -d secretpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
    external:
      name: traefik_network
